# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alertlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('ip', models.CharField(blank=True, default=b'', max_length=18)),
                ('port', models.CharField(default=b'', max_length=10)),
                ('statusinfo', models.CharField(blank=True, max_length=512)),
                ('insert_time', models.DateTimeField(default=datetime.datetime(2016, 9, 8, 6, 38, 1, 244535))),
                ('sendmail', models.IntegerField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='certinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1_fingerprint', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=50)),
                ('issuer_name', models.CharField(max_length=256)),
                ('issuer_orgname', models.CharField(max_length=256)),
                ('serial_number', models.CharField(max_length=256)),
                ('signature_algorithm', models.CharField(max_length=50)),
                ('publicKeyAlgorithm', models.CharField(max_length=50)),
                ('publicKeySize', models.CharField(max_length=40)),
                ('chain_order_valid', models.BooleanField()),
                ('ocsp_trusted', models.BooleanField()),
                ('notBefore', models.IntegerField()),
                ('notAfter', models.IntegerField()),
                ('trusted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='checkresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('ip', models.CharField(blank=True, max_length=18)),
                ('lastcheckts', models.IntegerField(default=0)),
                ('statuslevel', models.IntegerField(default=0)),
                ('statusinfo', models.CharField(blank=True, max_length=512)),
                ('heartbleed', models.IntegerField(default=0)),
                ('ccs', models.IntegerField(default=0)),
                ('hstc', models.IntegerField(default=0)),
                ('poodle', models.IntegerField(default=0)),
                ('certinfo_id', models.IntegerField(default=-1)),
                ('hostname_validation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FnascanMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('lastcheckts', models.IntegerField(default=0)),
                ('insert_time', models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 8, 14, 38, 1, 247358), null=True)),
                ('portinfo', models.TextField(blank=True, default=b'', null=True)),
                ('port_data', models.TextField(blank=True, default=b'', null=True)),
                ('statistics', models.TextField(blank=True, default=b'', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FnascanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('lastcheckts', models.IntegerField(default=0)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 8, 14, 38, 1, 245315), null=True)),
                ('update_service_name_time', models.DateTimeField(blank=True, null=True)),
                ('update_web_title_time', models.DateTimeField(blank=True, null=True)),
                ('update_port_status_time', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=18)),
                ('port', models.CharField(max_length=10)),
                ('service_name', models.TextField(blank=True, default=b'', null=True)),
                ('web_title', models.TextField(blank=True, default=b'', null=True)),
                ('service_detail', models.TextField(blank=True, default=b'', null=True)),
                ('port_status', models.BooleanField(default=True)),
                ('ip_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasscanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('lastcheckts', models.IntegerField(default=0)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 8, 14, 38, 1, 246507), null=True)),
                ('update_banner_time', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=18)),
                ('port', models.CharField(max_length=10)),
                ('banner', models.TextField(blank=True, default=b'', null=True)),
                ('port_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('port', models.IntegerField()),
                ('domain', models.CharField(max_length=80)),
                ('check_frequency', models.IntegerField()),
                ('notify_rule_id', models.IntegerField()),
                ('create_time', models.CharField(max_length=30)),
                ('heartbleed_check', models.BooleanField(default=False)),
                ('ccs_check', models.BooleanField(default=False)),
                ('hsts_check', models.BooleanField(default=False)),
                ('poodle_check', models.BooleanField(default=False)),
                ('status', models.IntegerField()),
                ('statusinfo', models.CharField(blank=True, max_length=512)),
                ('ports_check', models.BooleanField(default=False)),
            ],
        ),
    ]
