# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-09 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(blank=True, null=True)),
                ('inserted', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=32, null=True)),
                ('is_up', models.IntegerField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'result_ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultPorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(blank=True, null=True)),
                ('inserted', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=12, null=True)),
                ('protocol', models.CharField(blank=True, max_length=12, null=True)),
                ('product', models.CharField(blank=True, max_length=64, null=True)),
                ('product_version', models.CharField(blank=True, max_length=64, null=True)),
                ('product_extrainfo', models.CharField(blank=True, max_length=128, null=True)),
                ('scripts_results', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result_ports',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 9, 1, 37, 28, 822784)),
        ),
        migrations.AlterField(
            model_name='fnascanmetadata',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 9, 9, 37, 28, 825746), null=True),
        ),
        migrations.AlterField(
            model_name='fnascanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 9, 9, 37, 28, 823552), null=True),
        ),
        migrations.AlterField(
            model_name='masscanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 9, 9, 37, 28, 824840), null=True),
        ),
    ]
