# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20160912_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_monitor',
            name='remarks',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 2, 14, 52, 298481)),
        ),
        migrations.AlterField(
            model_name='fnascanmetadata',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 14, 52, 301146), null=True),
        ),
        migrations.AlterField(
            model_name='fnascanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 14, 52, 299366), null=True),
        ),
        migrations.AlterField(
            model_name='masscanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 14, 52, 300351), null=True),
        ),
    ]
