# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20160912_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 2, 17, 27, 907026)),
        ),
        migrations.AlterField(
            model_name='fnascanmetadata',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 17, 27, 909462), null=True),
        ),
        migrations.AlterField(
            model_name='fnascanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 17, 27, 907758), null=True),
        ),
        migrations.AlterField(
            model_name='masscanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 17, 27, 908756), null=True),
        ),
        migrations.AlterField(
            model_name='port_monitor',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 2, 17, 27, 904651)),
        ),
    ]
