# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20160912_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_monitor',
            name='fnascan_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port_monitor',
            name='masscan_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 2, 26, 44, 773550)),
        ),
        migrations.AlterField(
            model_name='fnascanmetadata',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 26, 44, 776060), null=True),
        ),
        migrations.AlterField(
            model_name='fnascanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 26, 44, 774298), null=True),
        ),
        migrations.AlterField(
            model_name='masscanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 26, 44, 775325), null=True),
        ),
        migrations.AlterField(
            model_name='port_monitor',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 2, 26, 44, 770977)),
        ),
    ]
