# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20160912_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='port_alive_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('port', models.IntegerField()),
                ('domain', models.CharField(max_length=80)),
                ('check_frequency', models.IntegerField()),
                ('notify_rule_id', models.IntegerField()),
                ('create_time', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('statusinfo', models.CharField(blank=True, max_length=512)),
                ('ports_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ssl_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('port', models.IntegerField()),
                ('domain', models.CharField(max_length=80)),
                ('check_frequency', models.IntegerField()),
                ('notify_rule_id', models.IntegerField()),
                ('create_time', models.CharField(max_length=30)),
                ('heartbleed_check', models.BooleanField(default=False)),
                ('ccs_check', models.BooleanField(default=False)),
                ('hsts_check', models.BooleanField(default=False)),
                ('poodle_check', models.BooleanField(default=False)),
                ('status', models.IntegerField()),
                ('statusinfo', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 2, 47, 55, 272720)),
        ),
        migrations.AlterField(
            model_name='fnascanmetadata',
            name='insert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 47, 55, 275185), null=True),
        ),
        migrations.AlterField(
            model_name='fnascanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 47, 55, 273356), null=True),
        ),
        migrations.AlterField(
            model_name='masscanresult',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 12, 10, 47, 55, 274407), null=True),
        ),
        migrations.AlterField(
            model_name='port_monitor',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 2, 47, 55, 269997)),
        ),
    ]
