# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20160912_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FnascanMetadata',
        ),
        migrations.DeleteModel(
            name='FnascanResult',
        ),
        migrations.DeleteModel(
            name='MasscanResult',
        ),
        migrations.DeleteModel(
            name='port_alive_project',
        ),
        migrations.DeleteModel(
            name='port_monitor',
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 3, 40, 34, 327509)),
        ),
    ]
