# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 03:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20160912_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 13, 3, 50, 56, 342962)),
        ),
    ]
