# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20160913_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certinfo',
        ),
        migrations.DeleteModel(
            name='checkresult',
        ),
        migrations.DeleteModel(
            name='ssl_project',
        ),
    ]
