# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portmonitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openport',
            name='remarks',
        ),
    ]
