# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portmonitor', '0003_openport_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openport',
            name='updateby',
        ),
    ]
