# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portmonitor', '0004_remove_openport_updateby'),
    ]

    operations = [
        migrations.AddField(
            model_name='openport',
            name='last_checkdetail_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
