# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portmonitor', '0005_openport_last_checkdetail_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_monitor',
            name='last_check_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
