# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portmonitor', '0006_port_monitor_last_check_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip_remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=80)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.CharField(blank=True, max_length=512)),
                ('own', models.CharField(blank=True, max_length=512)),
                ('remarks', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
