# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portmonitor', '0008_auto_20160922_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipremarks',
            name='doamin',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
