# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portmonitor', '0009_ipremarks_doamin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fnascanresult',
            old_name='lastcheckts',
            new_name='last_check_time',
        ),
        migrations.RemoveField(
            model_name='fnascanresult',
            name='ip_status',
        ),
        migrations.RemoveField(
            model_name='fnascanresult',
            name='update_port_status_time',
        ),
        migrations.RemoveField(
            model_name='fnascanresult',
            name='update_service_name_time',
        ),
        migrations.RemoveField(
            model_name='fnascanresult',
            name='update_web_title_time',
        ),
    ]
