# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portmonitor', '0010_auto_20160926_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FnascanMetadata',
        ),
        migrations.AddField(
            model_name='fnascanresult',
            name='ip_status',
            field=models.BooleanField(default=True),
        ),
    ]
