# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portmonitor', '0011_auto_20160926_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port_monitor',
            name='check_frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='port_monitor',
            name='fnascan_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='port_monitor',
            name='masscan_check',
            field=models.BooleanField(default=True),
        ),
    ]
